### ISSUE TITLE
When I try to open the permission tab on the ui I get this error

### ISSUE THREAD

**Issue by Player505** [simon816/TabbedChat#6]
The mods/plugins that I have at the time of this error are as followed 
`ChatUI-1.0.0.jar`
`spongeforge-1.12.2-2611-7.1.0-BETA-2914.jar`

And I am using the following forge server jar
`forge-1.12.2-14.23.2.2611-universal.jar`

This is the error that I get
`Error occurred while executing command 'sponge:callback 4d388d77-2804-4289-b770-bb0b7a6f2a5e' for source EntityPlayerMP['Player404'/541, l='world', x=-184.66, y=79.00, z=242.78]: org.spongepowered.api.service.permission.PermissionService.getKnownSubjects()Ljava/util/Map;
java.lang.NoSuchMethodError: org.spongepowered.api.service.permission.PermissionService.getKnownSubjects()Ljava/util/Map;
        at com.simon816.chatui.tabs.perm.PermissionsTab.createDashboard(PermissionsTab.java:84) ~[PermissionsTab.class:?]
        at com.simon816.chatui.tabs.perm.PermissionsTab.<init>(PermissionsTab.java:35) ~[PermissionsTab.class:?]
        at com.simon816.chatui.ActivePlayerChatView.lambda$initNewTab$2(ActivePlayerChatView.java:66) ~[ActivePlayerChatView.class:?]
        at com.simon816.chatui.tabs.NewTab$LaunchTabAction.lambda$new$0(NewTab.java:53) ~[NewTab$LaunchTabAction.class:?]
        at com.simon816.chatui.tabs.NewTab$LaunchTabAction.onClick(NewTab.java:62) ~[NewTab$LaunchTabAction.class:?]
        at com.simon816.chatui.tabs.NewTab$ButtonAction.accept(NewTab.java:35) ~[NewTab$ButtonAction.class:?]
        at com.simon816.chatui.tabs.NewTab$ButtonAction.accept(NewTab.java:28) ~[NewTab$ButtonAction.class:?]
        at com.simon816.chatui.ui.Button.lambda$draw$0(Button.java:75) ~[Button.class:?]
        at org.spongepowered.common.text.action.SpongeCallbackHolder.lambda$createCommand$0(SpongeCallbackHolder.java:96) ~[SpongeCallbackHolder.class:1.12.2-2611-7.1.0-BETA-2914]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2914]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2914]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2914]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2914]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:275) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2914]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]`

**Comment by simon816** [comment]
The problem is that you are using Sponge 7, whereas ChatUI 1.0.0 was made for Sponge 5 and 6.

Keep an eye out for updates to ChatUI. I plan to release the next version for Sponge 7.
In the meantime, you can either go back to an older Sponge version, or attempt to use ChatUI avoiding the features that don't work.
